function point = randInBounds(bounds)
    point = [rand * diff(bounds(1,:)) + bounds(1,1), ...
             rand * diff(bounds(2,:)) + bounds(2,1), ...
             rand * diff(bounds(3,:)) + bounds(3,1)];
end